---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: subdomain-mapper-acc

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subdomain-mapper
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: subdomain-mapper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: subdomain-mapper
subjects:
  - kind: ServiceAccount
    name: subdomain-mapper-acc
    namespace: default
