---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
spec:
  containers:
    - name: shell-operator
      image: nospamplease/monitor-services:v1
      imagePullPolicy: Always
  serviceAccountName: monitor-services-acc
