apiVersion: v1
kind: Service
metadata:
  labels:
    app: example-service
  name: example-service
  annotations:
    automatic-subdomain/ingress: "main-ingress"
spec:
  ports:
    - name: 80-80
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: example-service
  type: ClusterIP
